# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'retainCycle_demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for retainCycle_demo
  pod 'FBRetainCycleDetector'

  target 'retainCycle_demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'retainCycle_demoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
